# Creating Numpy Array

In [2]:
# np array

In [3]:
import numpy as np
a=np.array([10,20,30])
print(a)

[10 20 30]


In [4]:
#2D
a=np.array([[2,4,6],[1,3,5]])
print(a)

[[2 4 6]
 [1 3 5]]


In [5]:
#3D
x=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(x)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [6]:
#dttype
y=np.array([1.3,5,10.88], dtype=float)
y

array([ 1.3 ,  5.  , 10.88])

In [7]:
#np arrange
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
#with reshape
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.arange(81).reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [10]:
x=np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
y=np.zeros((4,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random((3,3))

array([[0.6894129 , 0.56478063, 0.1384522 ],
       [0.25194926, 0.71536614, 0.8979528 ],
       [0.66334576, 0.15931271, 0.37278437]])

In [13]:
i=np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Attributes

In [15]:
a= np.arange(10,dtype=np.int64)
b= np.arange(12,dtype=float).reshape(3,4)
c= np.arange(8).reshape(2,2,2)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [16]:
#size attribute
array1=np.array([1,2,3,44])
array1.size

4

In [17]:
#shape Attribute
y=np.array([[2,4,6],[1,3,5]])
y.shape

(2, 3)

In [18]:
#dtype Attribute
x=np.array([5,6,7,8])
x.dtype

dtype('int32')

In [19]:
#itemsize Attribute
a=np.array([5,7,8,8], dtype=np.int64)
a.itemsize

8

In [20]:
#data Attributes
a=np.array([4,6,7,89,4])
a.data #memory location Where array data is stored


### Indexing and Slicing

In [22]:
import numpy as np

In [23]:
#1D
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
a[6]

6

In [25]:
#2D
b=np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
b[2,2]

10

In [27]:
#3D
c=np.arange(125).reshape(5,5,5)
c

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [28]:
c[4,2,3]

113

In [29]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[3]

3

In [31]:
b=np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
b[2,1]

9

In [33]:
b[3,2]

14

In [34]:
c=np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
c[1,2,0]

15

In [36]:
d=np.arange(30).reshape(6,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [37]:
d[2,2]

12

In [38]:
e=np.arange(64).reshape(4,4,4)
e

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [39]:
e[2,3,3]

47

 # # Slicing

In [41]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a[0::2,1]

array([1, 9])

In [43]:
a[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [44]:
a[1:,1::2]

array([[ 5,  7],
       [ 9, 11]])

In [45]:
a[0:2,0::3]

array([[0, 3],
       [4, 7]])

In [46]:
a[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [47]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [48]:
a[1:,0::3]

array([[ 4,  7],
       [ 8, 11]])

In [49]:
a[1:2,0:2]

array([[4, 5]])

In [50]:
x=np.arange(49).reshape(7,7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [51]:
x[3::3,0:3]

array([[21, 22, 23],
       [42, 43, 44]])

In [52]:
a=np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
a[0::2,1]

array([[ 3,  4,  5],
       [21, 22, 23]])

In [54]:
y=np.arange(64).reshape(4,4,4)
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [55]:
#1 
y[0,0::3,0::3]

array([[ 0,  3],
       [12, 15]])

In [56]:
#2
y[1:4,0,0::3]

array([[16, 19],
       [32, 35],
       [48, 51]])

In [57]:
#3
y[0:4,1,1:3]

array([[ 5,  6],
       [21, 22],
       [37, 38],
       [53, 54]])

In [58]:
#4
y[0:4,1,0::3]

array([[ 4,  7],
       [20, 23],
       [36, 39],
       [52, 55]])

In [59]:
#5
y[3,3,0:2]

array([60, 61])

In [60]:
#6
y[3,3,1::2]

array([61, 63])

In [61]:
#7
y[0,1::2,1::2]

array([[ 5,  7],
       [13, 15]])

In [62]:
#8
y[3,1::2,2:4]

array([[54, 55],
       [62, 63]])

In [63]:
#9
y[0:2,2,1:3]

array([[ 9, 10],
       [25, 26]])

In [64]:
#10
y[2,0::3,2:4]

array([[34, 35],
       [46, 47]])

In [65]:
#11
y[3,1::2,1::2]

array([[53, 55],
       [61, 63]])

In [66]:
#12
y[2,2:4,1::2]

array([[41, 43],
       [45, 47]])

In [67]:
#13
y[0:2,2,1:3]

array([[ 9, 10],
       [25, 26]])

In [68]:
y=np.arange(64).reshape(4,4,4)
y
for i in y:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
[[48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]


import numpy as np

y = np.arange(64).reshape(4, 4, 4)

for i in y.flat:
    print(i)




# #  Fancing Indexing

In [70]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [71]:
arr=a[[1,0,4,2,3]]
arr

array([2, 1, 5, 3, 4])

In [73]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
arr=x[[0,1,2,3,3],[3,3,1,2,3]]
arr

array([ 3,  7,  9, 14, 15])

In [87]:
arr=x[[1,2,2,3],[1,2,3,2]]
arr

array([ 5, 10, 11, 14])

In [89]:
x=np.arange(64).reshape(4,4,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [111]:
arr=x[[3,3,2,2],[1,1,1,1],[0,1,0,1]]
arr

array([52, 53, 36, 37])

In [113]:
arr=x[[3,2,2,0],[3,0,0,2],[3,2,3,3]]
arr

array([63, 34, 35, 11])

# Broadcasting

In [144]:
a=np.arange(12).reshape(3,4)
b=np.arange(4).reshape(4)
c=a+b

In [146]:
c

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [148]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(4,1)
print(a+b)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]
